name: CICD Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: abhjtgt
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16

    # - name: Install Firefox
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y firefox

    - name: Setup Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: "143.0"
      
    - name: Build
      run: |
        echo "Installing dependencies..."
        npm install
        
    - name: check env
      run: | 
        firefox --version || true
        echo "PATH- $PATH"

    - name: Test
      run: |
        echo "Running tests..."
        npm test -- --browsers=FirefoxHeadless --watch=false
